spring:
  application:
    name: account-listing-service

  # --------------------
  # Database (external)
  # --------------------
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  # --------------------
  # Flyway (schema owner)
  # --------------------
  flyway:
    enabled: true

  # --------------------
  # Kafka (EXTERNAL)
  # --------------------
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

  # --------------------
  # Redis (cache)
  # --------------------
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 30s
      timeout: 2s