spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer
    username: postgres
    password: Salam
    hikari:
      maximum-pool-size: 50
  webclient:
    connect-timeout: 50ms

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  logging:
    level:
      org.hibernate.orm.boot: DEBUG
      org.hibernate.mapping: DEBUG
      org.springframework.retry: DEBUG

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: true

resilience4j:
  retry:
    instances:
      externalServiceRetry:
        max-attempts: 5
        wait-duration: 200ms
        exponential-backoff-multiplier: 2
        max-wait-duration: 5s
        retry-exceptions:
          - com.example.transfer.exception.TemporaryFailureException

  circuitbreaker:
    instances:
      fraudService:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

      externalServiceCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - com.example.transfer.exception.TemporaryFailureException

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

fraud:
  base-url: http://localhost:8082
  timeout-ms: 80