spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer
    username: postgres
    password: Salam
    hikari:
      maximum-pool-size: 50
  webclient:
    connect-timeout: 50ms

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  logging:
    level:
      org.hibernate.orm.boot: DEBUG
      org.hibernate.mapping: DEBUG
      org.springframework.retry: DEBUG

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  redis:
    timeout: 500ms

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: true

resilience4j:
  circuitbreaker:
    instances:
      fraudService:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true